//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject1.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chrome.
        /// </summary>
        internal static string CHROMEBROWSER {
            get {
                return ResourceManager.GetString("CHROMEBROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.musala.com/company/.
        /// </summary>
        internal static string COMPANYURL {
            get {
                return ResourceManager.GetString("COMPANYURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address entered is invalid..
        /// </summary>
        internal static string EMAILINVALIDERRORMESSAGE {
            get {
                return ResourceManager.GetString("EMAILINVALIDERRORMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/MusalaSoft?fref=ts.
        /// </summary>
        internal static string FACEBOOKURL {
            get {
                return ResourceManager.GetString("FACEBOOKURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firefox.
        /// </summary>
        internal static string FIREFOXBROWSER {
            get {
                return ResourceManager.GetString("FIREFOXBROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.musala.com/careers/join-us/.
        /// </summary>
        internal static string JOINUSURL {
            get {
                return ResourceManager.GetString("JOINUSURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The telephone number is invalid..
        /// </summary>
        internal static string MOBILEINVALIDERRORMESSAGE {
            get {
                return ResourceManager.GetString("MOBILEINVALIDERRORMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required..
        /// </summary>
        internal static string REQUIREDERRORMESSAGE {
            get {
                return ResourceManager.GetString("REQUIREDERRORMESSAGE", resourceCulture);
            }
        }
    }
}
